spring.application.name=idp
spring.output.ansi.enabled=always
server.port=8083
frontend.login.url=https://localhost
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.domain=.localhost
